command-permissions:
  # true: all
  # not op: only non-op player
  # op: only op player
  kitload: op
  kitsave: op
  kitremove: op
  kitreload: op
permission-message: "&cYou don't have permission to use this command."
