name: kitload
version: $version
main: io.github.bruce0203.kitload.Plugin
api-version: 1.19
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.7.20
  - org.jetbrains.kotlin:kotlin-reflect:1.7.20
  - org.jetbrains.kotlin:kotlin-test:1.7.20
commands:
  kitload:
    permission: kitload
  kitsave:
    permission: kitsave
permissions:
  kitload:
    default: op
  kitsave:
    default: op